{{- $root := . -}}
{{- range $image, $imageValue := .Values.images }}
{{- if $imageValue.regcred }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  labels:
    app.kuberentes.io/name: {{ include "wlanonboard.name" $root }}
    helm.sh/chart: {{ include "wlanonboard.chart" $root }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
    app.kubernetes.io/managed-by: {{ $root.Release.Service }}
  name: {{ include "wlanonboard.fullname" $root }}-{{ $image }}-regcred
data:
  .dockerconfigjson: {{ $imageValue.regcred | quote }}
{{- end }}
{{- end }}
