---
apiVersion: v1
metadata:
  labels:
    app.kuberentes.io/name: {{ include "freeradius.name" . }}
    helm.sh/chart: {{ include "freeradius.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "freeradius.fullname" . }}-configs
kind: Secret
type: Opaque
data:
  users: {{ .Values.users_data | b64enc | quote }}
  clients: {{ .Values.clients_data | b64enc | quote }}
  extraSite: {{ .Values.extra_site | b64enc | quote }}
