---
apiVersion: v1
metadata:
  labels:
    app.kuberentes.io/name: {{ include "freeradius.name" . }}
    helm.sh/chart: {{ include "freeradius.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "freeradius.fullname" . }}-env
kind: Secret
type: Opaque
data:
  # Secret env variables
  {{- range $key, $value := .Values.secret_env_variables }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}

