name: Helm validation

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validators setup
        run: |
          mkdir /tmp/k8s-validators
          cd /tmp/k8s-validators

          curl -LO https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
          tar xf kubeval-linux-amd64.tar.gz
          rm -f kubeval-linux-amd64.tar.gz LICENSE README.md

          curl -LO https://get.helm.sh/helm-v3.2.4-linux-amd64.tar.gz
          tar xf helm-v3.2.4-linux-amd64.tar.gz
          mv linux-amd64/helm .
          rm -fr helm-v3.2.4-linux-amd64.tar.gz linux-amd64
      - name: Cache validators
        uses: actions/cache@v1
        with:
          path: /tmp/k8s-validators
          key: ${{ runner.os }}-k8s-validators
      - name: Test freeradius helm chart
        working-directory: freeradius/helm
        run: |
          echo "Helm lint test"
          helm lint .

          echo "Kubeval test"
          helm template -f values.yaml . | /tmp/k8s-validators/kubeval --ignore-missing-schemas
